dependencies:
- name: act3-prod-gen-prototype
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.21
- name: act3-workflow-management
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.14
- name: act3-workflow-management-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.17
- name: alex
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.16
- name: alex-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: aplos-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.105
- name: cvdi
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.1.12
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: expressway
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.43
- name: flisr-c
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.65
- name: flisr-c-backend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.13
- name: fuelai
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.28
- name: humant-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.33
- name: humant-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.10
- name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 7.0.2
- name: projects
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.16
- name: purifile-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.12
- name: purifile-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.200
- name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 6.4.5
- name: rope-prototype
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.16
- name: tech-suite
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.12
- name: techplan-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.16
- name: techplan-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.38
- name: techscout-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.47
- name: techscout-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.79
- name: windrose
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: workflow-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.2.17
- name: workflow-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.17
